81 categories
luchogabutti/reddit pull request #3
Opened 2023-05-23 14:36 UTC by luchogabutti

Linear card;

https://linear.app/cuadernorojo/issue/CR-81/listado-de-categorias

2023-05-23 15:22 UTC, noelsp requested changes

2023-05-23 15:22 UTC, noelsp commented on src/screens/home/components/subreddits/index.jsx
> +            <h2>Subreddits</h2  >
fix `</h2> `

2023-05-23 15:22 UTC, noelsp commented on src/screens/home/components/subreddits/index.jsx
> +export default Subreddits
Add end of file here

2023-05-23 15:22 UTC, noelsp commented on src/screens/home/components/subreddits/style.css
> +}
Add end of file

2023-05-23 15:22 UTC, noelsp commented on src/screens/home/index.jsx
>              <Header/>
`<Header />`

2023-05-23 15:22 UTC, noelsp commented on src/screens/home/index.jsx
>              <Articles/>
Indentá y agregá `<Articles />`

2023-05-23 15:22 UTC, noelsp commented on src/screens/home/style.css
> +    }
End of file: 

Adjust "}"
```
.main {
    display: flex;
    justify-content: center;
 }
```

2023-05-23 15:22 UTC, noelsp commented on src/screens/home/components/subreddits/index.jsx
> +            {subreddits && subreddits.map(subreddit => <Subreddit key={subreddit.id} subreddit={subreddit.data}/>)}
Deconstruct the map param: 

`{subreddits && subreddits.map(({id, data}) => <Subreddit key={id} subreddit={data}/>)}`

2023-05-23 15:29 UTC, luchogabutti commented on src/screens/home/components/subreddits/index.jsx
> +            <h2>Subreddits</h2  >
done

2023-05-31 13:31 UTC, noelsp approved these changes

2023-05-31 19:04 UTC, merged